apel/ssm

bin/receiver.py
ssm/crypto.py
ssm/ssm2.py

Resolves #23.
These changes tidy up the log output of SSM, by reducing the amount of uninteresting log entries,  and make it a bit more useful, by specifying the queue location that messages are saved to.
```
2015-02-11 08:00:57,585 - ssm.ssm2 - INFO - Received message: 00000000/20150211080307
2015-02-11 08:00:57,642 - ssm.crypto - INFO - Certificate verification: stdin: OK
2015-02-11 08:00:57,653 - ssm.crypto - INFO - Verification successful
2015-02-11 08:00:57,663 - ssm.ssm2 - INFO - Valid signer: /C=OK/O=SomeGrid/O=ABC/CN=arc-ce.grid.abc.de
```
```
2015-02-11 08:00:57,585 - ssm.ssm2 - INFO - Received message. ID = 00000000/20150211080307
2015-02-11 08:00:57,663 - ssm.ssm2 - INFO - Valid signer: /C=OK/O=SomeGrid/O=ABC/CN=arc-ce.grid.abc.de
2015-02-11 08:00:57,663 - ssm.ssm2 - INFO - …
```

Improving SSM logging

---

.travis.yml
requirements.txt

As per apel/apel#74.
- Activate Travis containerization in Travis file.
- Add caching of pip.
- Move pip install requirements to requirements.txt and remove pip install
list so that Travis runs the default pip install command so that the pip
cache works.
- Add comments.

Activate Travis containerization

---

bin/receiver.py

Workaround for issue #26, but a proper fix should be found for that.
This delays the attempt to reconnect for ten minutes by which time broker problems are generally resolved.

Add delay to receiver restart on lost connection

---

.travis.yml

As per apel/apel#105.
- Remove Python 2.7 from allowed failures as we should now be building for
OSes that have it as default.
- Update Python 3.4 to 3.5 as we should just check the latest available.

Update Python versions in Travis file

---

test/test_crypto.py

This means we wont have to regenerate the hard coded values once a year.
I have removed the hard coded values and replaced them with constants that should contain the key, cert and ca directory path. Keys, certs and ca files are then generated for each test.
most of the changes were simply 
* `self.certpath` and `self.keypath` to `TEST_CERT_FILE` and `TEST_KEY_FILE`
* `self.ca_dir` to `TEST_CA_DIR`
I also removed `test_from_file`, as there is no need to check the file contains the certificate it should, as the cert file is now dynamically generated
Encrypted or signed messages are generated in the test case if needed. they could be done in `setUp` but are only needed for a few test cases.

Replace hard coded cert/key used in testing with generated ones

---

.travis.yml

Same as for apel/apel#134.
Change Travis file to test against latest nightly rather than a fixed Python 3 version so that it doesn't have to continually be manually changed.
At the moment this will be Python 3.7.0a0.

Change Travis file to test against Python nightly

---

.travis.yml
requirements.txt

Same as for apel/apel#137.
- Remove pip log before caching to avoid it affecting the cache.
- Add --branch argument to coverage run in preparation for coveralls
module reporting coverage to Coveralls.io.
- Add mock to requirements and add final newline.

Tweak Travis build

---

apel-ssm.spec

Closes #35.
Rebased version of #35 with additional comment. As this change doesn't affect our builds due to the conditional, I'm okay with the build requirement of python-devel, even though this seems to be over specifying the package required (only python is actually needed to build as this isn't a Python extension - which would require python-devel).

Alphacc patch 1

---

scripts/ssm-build-rpm.sh

Resolves #37.
Very similar to the one for APEL added in apel/apel#122. Main difference is the leading asterisk in the cleanup and a `.sh` file extension. Also adds a scripts folder for the first time to SSM.

Initial commit of RPM build script

---

bin/receiver.py

- Merge refresh and ping log messages into one as don't really need to
have two when they always occur together.
- Reduce logging level of connection lost to warning as software is
still working correctly.

Merge two log messages into one and change level

---

setup.py

As it is not installed by the RPM and having it installed causes confusion when the logging config section is only specified in the sender or receiver config but `logging.cfg` is under `/etc/apel`, as in that case it takes precedence over the supplied configs logging section.

Stop setup.py installing /etc/apel/logging.cfg

---

conf/logging.cfg

Resolves #57.
`logging.cfg` seems to have only ever caused problems. So some explanatory comments should help avoid problems.

Add comment to logging.cfg to clarify usage

---

conf/sender.cfg
ssm/ssm2.py
test/test_ssm.py

Follow on from #40. This is fairly minor and in a sense fixes an issue for clients so I'm including it in 2.2.1.
This PR:
- changes the comment in the config for `server_cert` to clarify its usage
- adds checking of the server cert expiry
- adds corresponding unit test
- tidies a little whitespace.

Expired server cert check

---

ssm/crypto.py
ssm/ssm2.py

Partially resolves #62. (Will write up remaining issue separately.)
1. Add `try...except` to catch `ValueError`s raised when there's no blank line
beween header and body of an otherwise valid signed message. Raising a
`CryptoException` means that the message will be rejected nicely in
`Ssm2.on_message`.
1. Catch `IOError` in addition to `OSError` in `on_message` as there is [no real
difference between them](https://www.python.org/dev/peps/pep-3151/#confusing-set-of-os-related-exceptions) and we sometimes get the former being raised.
Part 1 allows the message to be written out to the reject queue. 2 doesn't, but it's an odd situation that will need some more work - see #64.

Add handling for unhandled exceptions

---

README.md
apel-ssm.spec
requirements.txt
setup.py
ssm/ssm2.py

resolves #7 
This also removes support for stomp.py v2 and most likely v3.0. Those versions are not pip installable so I can't confirm.
* rework `_initialise_connection` to do everything in the connection constructor. Previously some attributes were set after the constructor to support stomp.py v2. 
* rework `start_connection`, `on_send` and `_send_msg` to support v3.1.6+ and v4
* replace a call to `stop()` with `disconnect()` as they are functionally the same in v3 and `stop()` does nothing in v4
* add an `on_receiver_loop_completed` handler to reduce some of the noise from stomp.py v4
* removes version constraint in requirements.txt for stomp.py

Add support for stomp.py v3.1.6+, including stomp.py v4

---

README.md
apel-ssm.spec
requirements.txt
setup.py

- It seems python-daemon 2.2.0 released on 15/08/2018 breaks
support for python 2.6.
- The obvious effect is the travis tests and docker build
started to fail this morning.
- Freezing this package should allow the tests and builds to pass
Example of failed Travis test:
```
Collecting python-daemon (from -r requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/99/2a/75fe6aa7086e838570f29899f674e7896a42be26d9fff33f90d990e599d2/python-daemon-2.2.0.tar.gz (79kB)
100% |████████████████████████████████| 81kB 6.0MB/s 
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-rHUVES/python-daemon/setup.py", line 21, in <module>
import version
File "version.py", line 520
for item in …
```

Freeze python-daemon at 2.1.X

---

scripts/ssm-build-deb.sh

- Pip is needed for fpm. This was missing before so would lead to error during the build.
- Apt-get install commands collapsed to single line to save copy pasting.
Tested on a fresh Ubuntu Trusty VM.

Collapse apt-gets to single line and add pip

---

.travis.yml
constraints.txt
requirements-test.txt
requirements.txt

The weekly cron build failed which raised an issue with a dependency of a dependency not supporting Python 2.6 any more. This PR fixes that (though the longer term fix is to deprecate Python 2.6 support).
- Move test requirements into separate requirements file to make it
clearer that they are only needed for running unit tests.
- Add constraints file called from the test requirements file to limit
one of coveralls' dependencies to an earlier version that works with
Python 2.6.

Split test requirements out and add constraint

---

.travis.yml
CHANGELOG
README.md
apel-ssm.spec
constraints.txt
requirements-test.txt
requirements.txt
scripts/ssm-build-deb.sh

May magically be approved if #86 is.

Release 2.3.0-2 to master

---

ssm/ssm2.py

Resolves #92.
The key parts of this change are the swap from `self._conn.connect(wait=True)` to `=False` and the removal of the raising of an exception in `on_error` - these changes allow SSM to retry the connection after a timeout (rather than blocking) and to then exit gracefully once all brokers have been tried.
`start_connection` has been rearranged to check if connected just after connecting, rather than after creating a subscription, so that a subscription is not attempted without a connection. This is to mitigate the removal of the connection wait.
Additionally, the error message you get if you try to connect without being authorised has been improved (no more Java error dump!) and the version of stomp.py in use is logged.
Example output:
```
2019-03-06 14:03:37,150 - ssmsend - …
```

Fixing of on_error exception hanging

---

ssm/crypto.py
ssm/ssm2.py
test/test_ssm.py

Resolves #96. Note that this will be merged into the release branch.
`-checkend` should be followed by a number that defines how many seconds ahead `openssl x509` should check for cert expiry, otherwise later versions of OpenSSL raise syntax errors (treating next arg as the number). Set it to a day as certs should really be renewed before that considering the amount of time it can take a message to traverse the messaging system.
Other minor changes to exception messages and tests in support of this.

OpenSSL checkend fix

---

CODEOWNERS

This file will mean that when a pull request is opened, everyone
in the code-reviewers team will be requested for review.

Add basic CODEOWNERS file to simplify code reviews

---

bin/apel-ssm

Replace tabs used for code alignment with spaces

---

ssm/ssm2.py

As for c8dcf5b953b7 which was included in #52, we want to limit the log spam we get from a 3rd-party module.
- Add log level setting for `connectionpool` logging, to the code that
already handles setting `stomp.py` logging, otherwise `connectionpool`
generates a lot of "Starting new HTTPS connection" messages at the
INFO level that we aren't really interested in.

Limit urllib3 logging based on overall level

---

ssm/crypto.py
test/test_crypto.py

One such reason is the message has been tampered with after being signing. Therefore this resolves #39.

Raise CryptoException if signed message verification fails (for whatever reason).

---

.travis.yml
README.md
apel-ssm.spec
constraints.txt
requirements-test.txt
requirements.txt
setup.py

Resolves #113.
This PR removes the Python 2.6 build and the dependency version constraints that were required to maintain compatibility. It does however constrain the version of python-daemon to maintain Python 2.7 compatibility.

Build update

---

.travis.yml
bin/receiver.py
bin/sender.py
ssm/brokers.py
ssm/crypto.py
ssm/message_directory.py
ssm/ssm2.py
test/test_brokers.py
test/test_crypto.py
test/test_message_directory.py
test/test_receiver.py
test/test_ssm.py

Partially addresses #91.
**N.B. Removes support for Python 2.6.** So we'll need to go up a major (!) version number for the next release.
This pull request adds basic Python 3 compatibility such that the Travis tests can run successfully. There are certainly other things that will need fixing to ensure SSM actually works with Python 3 (including `optparse` deprecation).
References for `quopri` changes:
[Python 2](https://docs.python.org/2/library/quopri.html)
[Python 3](https://docs.python.org/3/library/quopri.html)

Drop Python 2.6, add Python 3 test compatibility

---

.travis.yml
requirements-test.txt
setup.py

- Remove unittest2 as Py 2.6 support isn't require
- Remove arguments to `setup()` related to the `test` command as this has been deprecated in the latest versions of setuptools.

Remove unittest2 and deprecated setup() arguments

---

README.md
apel-ssm.spec
bin/receiver.py
setup.py
ssm/ssm2.py

This resolves #95 by addressing most of the items in the issue.
- `argo-ams-library` has been made optional.
- Duplicated code between AMS and STOMP methods has been factored out to `_save_msg_to_queue`.
- AMS send message function has been factored out to `_send_msg_ams`.
It doesn't pull out AMS and STOMP functions to their own files, but that's a larger thing that is probably dependant on `stomp.py` being made optional (but it has a lot of low level integration in the code). Follow up issue in #120.

95 refactor

---

bin/receiver.py
bin/sender.py

Resolves #111.
- Move use_ssl setting outside broker catch block as `use_ssl` was only getting set if the broker was being retrieved from the BDII. If it was configured manaully, `use_ssl` wasn't set and SSM would
break. This change means it will get set either way.
- Add default True value for fetched `use_ssl` values so that there's no issue if `use_ssl` isn't set in the config files.

Manual broker use_ssl fix

---

bin/receiver.py
ssm/ssm2.py

- Fix regression from 65971ae
- The sleep was intended to limit the speed of the while loop that waited
for the STOMP message to be accepted, but this got moved outside the
while loop when AMS support was added, which does not seem sensible.
-  Speed up receiver loop
- Speed up receiver loop by decreasing sleep as pulling a message only
once a second doesn't seem very efficient. The value of REFRESH_DNS
needs is increassed ten-fold to balance out the change in sleep.

Sleep tweaks

---

ssm/ssm2.py

Resolves #134.
This is backwards compatible as the AMS methods all have a **kwargs argument in the previous versions.

Add retry=3 to AMS methods for reliability

---

CHANGELOG
apel-ssm.spec

Whoops!
This PR corrects the spelling of the month in the changelogs. Merging into `master` is intentional.

Hotfix 3.1.0-2

---

migrating_to_ams.md

This PR updates the docs to use the production host for AMS and corrects a spelling error and fixes the indentation with GitHib Markdown seems to be fussier about it when you have code sections in the middle of numbered lists.

Update and fix AMS migration documentation

---

ssm/ssm2.py

Something seems to have changed behind the scenes with has required tweaking the logging for urllib3 again as we did in #105. This could have been a change in AMS, its library, or something peculiar to our installation on our prod machine (this behaviour wasn't seen on pre-prod).

Add another urllib logging tweak

---

migrating_to_ams.md

They use dashes rather than dots.
As discovered when dealing with [this ticket](https://ggus.eu/index.php?mode=ticket_info&ticket_id=150029).

Correct topic names in AMS migrate docs

---

bin/sender.py

Resolves #110
New log output:
```
2020-12-09 11:51:05,233 - ssmsend - INFO - Found 2 brokers.
2020-12-09 11:51:05,254 - ssmsend - INFO - Messages will be encrypted using /C=Bacon/O=Baked Beans/O=Eggs/CN=apel.server
2020-12-09 11:51:05,267 - ssmsend - INFO - Messages will be signed using /C=Bacon/O=Baked Beans/O=Eggs/CN=client.box
```

Adds server and host dns to the sender log

---

scripts/ssm-build-deb.sh

Add stomp.py DEB dependency to match other OSes

---

migrating_to_ams.md

This clarifies the AMS requirements and adds guidance on what can be done if messages are too large for the AMS 1 MB limit.

Migration doc update

---

apel-ssm.spec
scripts/ssm-build-deb.sh

Resolves #158 
openssl is a dependency of SSM, but it is called using suprocess so it's not the most obvious failure if it's not installed.
Draft while I test the build.

Add openssl as dependency for rpm and deb builds

---

ssm/crypto.py
test/test_crypto.py

Resolves #124.
Changes in the verification of key/cert matching, to correct the bug in issue #124 
The new verification algorithm makes use of suggestions in https://security.stackexchange.com/a/143981 to compare the public key extracted from both the certificate and the private key.
```
openssl x509 -pubkey -in mydomain-ecc.crt -noout
openssl pkey -pubout -in mydomain-ecc.key
```

generalize certificate and a key matching verification to admit both RSA and EC keys

---

scripts/ssm-build-rpm.sh

Not every build system will have access to fedora-packager, but only a
subset of what's included with that is actually required.

Specify more specific rpms for build

---

README.md
apel-ssm.spec
ssm/agents.py

Resolves #80
As there's no consistent way of handling optional packages across packaging systems, python-daemon should just be left out.

Remove python-daemon as a requirement 

---

requirements.txt

python-ldap-3.4.0 dropped support for Python 2: https://github.com/python-ldap/python-ldap/releases/tag/python-ldap-3.4.0

Cap python-ldap below 3.4.0

---

requirements-test.txt

- version 4 dropped support for Python 2.7

Cap mock below 4.0.0

---

.github/workflows/unit-test.yml

- This means that every job will run, whatever the result of any other.

Set GH Action unit test matrix to not fail fast

---

apel-ssm.spec
requirements.txt
setup.py
ssm/agents.py
ssm/ssm2.py

Resolves #164
Log output for sender.py:
<pre><code>
2021-08-17 14:46:40,595 - ssmsend - INFO - ========================================
2021-08-17 14:46:40,595 - ssmsend - INFO - Starting sending SSM version 3.2.1.
2021-08-17 14:46:40,595 - ssmsend - INFO - Setting up SSM with protocol: AMS
2021-08-17 14:46:40,596 - ssmsend - INFO - No AMS token provided, using cert/key pair instead.
2021-08-17 14:46:40,596 - ssmsend - INFO - No server certificate supplied.  Will not encrypt messages.
<b>2021-08-17 14:46:40,596 - ssmsend - INFO - Configured destination queue: gLite-APEL</b>
2021-08-17 14:46:40,612 - ssmsend - INFO - Messages will be signed using /C=UK/L=Harwell/O=UKRI/OU=SCD/CN=host-172-16-113-220.nubes.stfc.ac.uk
SSM failed to complete successfully.  See log file for details.
2021-08-17 …

164 log the topic

---

README.md

- as it has changed following DockerHub's removal of free Team organizations.

GT-143: Update docker container location

---

.github/workflows/build-pkgs.yml
.github/workflows/codeql-analysis.yml

The condition given to `cron` JOB helps us to NOT trigger the event in a fork branches. And, It will only trigger the CRON Job if it is DEV branch.
"Resolves #211"

[GT-151] - Action jobs should be disabled in non-upstream repos

---

test/test_crypto.py

- removes old comment
- gets rid of logging.getLogger('SSM')
resolves #244
test output:
```
[root@host-172-16-105-234 test]# python test_crypto.py
Generating a 2048 bit RSA private key
................................+++
................................................................+++
writing new private key to '/tmp/test.key'
-----
.Generating a 2048 bit RSA private key
..+++
............................................................................+++
writing new private key to '/tmp/test.key'
-----
ERROR:ssm.crypto:unable to load certificate
140315647899536:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: TRUSTED CERTIFICATE
.Generating a 2048 bit RSA private key
.........................................+++ …
```

[GT-185] Update logging in test_crypto

---

ssm/ssm2.py

else case and return added to issue 242

---

ssm/ssm2.py

Resolves #243
Adding timeouts to resolve issue #243 - currently set to 10 second timeouts.  
Difficult to consistently unit test for, so manual testing was done by blocking the TCP connection through TCPKill and sending Fallocate-d 512kb messages through and watching the TCP traffic.  Timeouts successfully call the underlying requests library, and no longer indefinitely looks for a connection.  Tested on a scientific Linux 7 distro running python 3.6.8 and 2.7.5.

Minor timeout changes

---

requirements.txt

Resolves #257 
- 2020.4.5.2 dropped Python 2 support, https://github.com/certifi/python-certifi/commit/5efdd48f719d9c3c7c8f9a812da2256d088eab78
- `certifi` is used by `requests`, which is used by `argo-ams-library`
This resolves the syntax error shown in the issue and I have tested the SSM to the point where the ARGO Messaging Service says my dev environment isn't authorised to sent messages.

Cap version of certifi used below 2020.4.5.2

---

README.md

As reported in #257, the documentation for running a containerized receiver references the wrong config file (`sender.cfg`) and refers to the `/outgoing` message directory.

Fix copy/paste error in receiver docs

---

ssm/message_directory.py
test/test_message_directory.py

resolve #235 
I was unsure which files needed to be checked but I think checked the right ones so they are only appended if they are files that exist.

File check. Issue235

---

Dockerfile
requirements.txt
ssm/crypto.py
test/test_crypto.py

Resolves #167 
At @jrha 's suggestion, to solve a formatting conflict, this PR adds pyOpenSSL as a dependency and uses it to handle the distinguished name formatting.  pyOpenSSL isn't currently used for anything else.

OpenSSL compatibility fix

---

scripts/ssm-build-dual.sh
scripts/ssm-build.sh
setup.py

Resolves #123 
Resolves GT-253
This PR adds a build script that supersedes ```ssm-build-rpm.sh``` and ```ssm-build-deb.sh``` by adapting the FPM calls made in the original Debian script and adding configurable parameters.  It works with Python 2.7 and >= 3.6, and requires FPM 1.14.2 and a version of Ruby at or above 2.7, as well as specifically Setuptools==51.3.3.  It allows a version to be specified to pull from the repository and be setup.
Usage: ```./ssm-build-dual.sh [options] (deb | rpm) <version> <iteration> <python_root_dir>```
Currently, this should work for all future versions and all the past RPM versions: Debian, it doesn't work for before the coming 3.4.0 update due to CHANGELOG having a title.

FPM build script for RPM and DEB

---

conf/receiver.cfg
conf/sender.cfg

Resolves #200 
- Set AMS as default messaging system.
- Add AMS hosts (both prod and devel) as options.
- Emphasise note about the server_cert.
- Add token as commented out option.
- Copy log level comments from sender to receiver conf.

Update comments and options in config files

---

requirements.txt
setup.py
ssm/ssm2.py
test/test_ssm.py

Resolves #146 
Resolves #209 
Note that this is a conservative fix and does not add Unicode support so that the behaviour matches between Python 2 and 3.
Unicode support is tracked in #299.
Tested manually between Python 2 and 3, sending and receiving for each, and using `dirq` and `directory` sending.

Character vs. byte strings fix

---

ssm/agents.py

Resolves #295 
this traces back the error to the line in the code
Before:
```
2024-04-04 15:43:27,858 - ssmsend - INFO - ========================================
2024-04-04 15:43:27,858 - ssmsend - INFO - Starting sending SSM version 3.4.0.
2024-04-04 15:43:27,858 - ssmsend - INFO - Setting up SSM with protocol: AMS
SSM failed to complete successfully.  See log file for details.
2024-04-04 15:43:27,858 - ssmsend - ERROR - Unexpected exception in SSM: msg
2024-04-04 15:43:27,858 - ssmsend - ERROR - Exception type: <class 'ValueError'>
2024-04-04 15:43:27,858 - ssmsend - INFO - SSM has shut down.
2024-04-04 15:43:27,858 - ssmsend - INFO - ========================================
```
After:
```
2024-04-04 15:44:13,693 - ssmsend - INFO - ========================================
2024-04-04 …
```

Changed the unexpected log.error to use log.exception

---

ssm/crypto.py

Resolves #313
Solves original problem of a warning returned by Popen as an error and causing the function to return False
Improves the variable names from pubkey1 and pubkey2 to help show where the key came from

Replaced the Popen commands in check_cert_key to use OpenSSL

---

ssm/agents.py

Resolved #160
added sender_failed = True to an exception to properly show it failed

Checks wether the host cert is the same as server cert for sender if it is then an error message is given

---

scripts/ssm-build.sh

[fcb58cb29e5ba0694d17c4e424885075a2b9da96] Will generate OS specific rpms with the python path targeting the specific OS.
[4d889d8b2a3cdb84a31c3c6b7385fcd099f8a465]: When we are using this `ssm-build.sh`. This commit will help to say python where to install the scripts to. Added this because it is by default installing ssmreceive and ssmsend to /usr/local/bin.
[4d889d8b2a3cdb84a31c3c6b7385fcd099f8a465] Added because `pleaserun` has `/usr/bin/ssmreceive` as the file to work with.

Issue with ssm rpm build in el9

---

scripts/ssm-build.sh

7952bc5
This commit will allow to run the file in home directory and perform rpmlint checks in an given pwd location(Say, when running the FPM script with -s and -b).

Fix rpmlint to perform rpm checks in given location

---

setup.py

Resolves https://github.com/apel/ssm/issues/296
Resolves [GT-331]
Now  will make use of build step to install the package and enabling separate flows for build and install phases. It also now supports basic commands for setup in [cf905c53b356e4681441cc9970dd828f3e4aa336].
[GT-331]: https://stfc.atlassian.net/browse/GT-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

setup.py to build and install the package underneath

---

bin/receiver.py
bin/sender.py

The `exit()` function is from site.py which may not be present depending on command line options. `sys.exit` on the other hand, will be there as it is imported.

Change `exit()` to `sys.exit()`

---

bin/receiver.py
bin/sender.py
ssm/agents.py

Replaced upper case ConfigParser for python 2 with the lower case python 3 version configparser
resolves #365

Removed except ImportError python 2 checks for configparser

---

bin/receiver.py
bin/sender.py

Optparse is deprecated - no longer developed. Mostly a like-for-like replacement, but we use vars on the argparse object to output the values in a similar way to optparse.
The old version option on the constructor is unavailable, and so it has been replaced by adding an argument with the 'version' action.
Resolves #275
Resolves GT-540

Replace optparse with argparse

---

README.md
apel-ssm.spec
scripts/ssm-build.sh
setup.py

This PR updates a bunch of little things now that we no longer need Python 2 support. Mainly:
- Update README
- Update SPEC file so it stays mostly in step with new build script.
- Update build script to remove Python 2 option.
- Update min AMS library version in setup.py.
Resolves #216 
Resolves #333

Update build and deps

---

scripts/ssm-build.sh

- Remove  `python3-daemon` dependency from the base package. And, add `python3-daemon` for `apel-ssm-service` as it is required.
Resolves #371 
Resolves [GT-555]
When installing the service: Now  python3-daemon  will be installed as part of the service.
Installing:
apel-ssm-service                noarch                3.4.1-1.el9                    @commandline                 13 k
Installing dependencies:
python3-daemon                  noarch                2.3.2-1.el9                    epel                         46 k
[GT-555]: https://stfc.atlassian.net/browse/GT-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add extra dependencies for apel ssm service

---

bin/receiver.py
bin/sender.py

Refactor argument parsing to use argparse Namespace object for structured access.
Closes #374

Simplify argparse usage

---

conf/sender.cfg

Resolves #375 in a slightly different way to suggested.
We don't want people accidentally sending to the production host, but we also don't want people to accidentally send to the devel host if not intended. So remove the default host and add the list of hosts to a comment, explaining the purpose of each.
Also uncomment the port option and clarify its usage. It does nothing for AMS sending, so might as well leave it uncommented.

Remove default host and tidy comments
